### ISSUE TITLE
Tire model unavailable

### ISSUE THREAD

**Issue by aiyan327** [mathworks/Simscape-Vehicle-Templates#1]
Hello,

I'm trying to run the CRG Mallory map, which requires the MF-Swift or Delft tire models. I've checked the available tire models in VDatabase and I've carefully selected the configuration options. 

But it always gives error message that I'm selecting an unavailable tire model. Only MFEval could work. Is there anything I got wrong here?

**Comment by smiller01985** [comment]
Hi aiyan327 - MFEval is provided within the repository.  MF-Swift must be installed separately.  You can obtain MF-Swift software from the MATLAB Add-on Explorer: 
![MF_Tyre_MF_Swift_AddOnExplorer](https://github.com/mathworks/Simscape-Vehicle-Templates/assets/56474268/7d8d5ddf-1d70-491a-af85-4f9af04576a2)

Also note that Simscape Multibody has a Magic Formula Tire model as well.
[Magic Formula Tire Force and Torque](https://www.mathworks.com/help/sm/ref/magicformulatireforceandtorque.html)

**Comment by aiyan327** [comment]
Thank you so much! The error is gone now.
